### ISSUE TITLE
LOAD chsql_native  ERROR

### ISSUE THREAD

**Issue by LeeMo2K10** [quackscience/duckdb-extension-clickhouse-native#6]
IO Error: Extension "/Users/mo/.duckdb/extensions/v1.1.3/osx_amd64/chsql_native.duckdb_extension" could not be loaded: dlopen(/Users/mo/.duckdb/extensions/v1.1.3/osx_amd64/chsql_native.duckdb_extension, 0x0006): tried: '/Users/mo/.duckdb/extensions/v1.1.3/osx_amd64/chsql_native.duckdb_extension' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/mo/.duckdb/extensions/v1.1.3/osx_amd64/chsql_native.duckdb_extension' (no such file), '/Users/mo/.duckdb/extensions/v1.1.3/osx_amd64/chsql_native.duckdb_extension' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))

**Comment by lmangani** [comment]
Hey @LeeMo2K10 thanks for the report! I don't have an OSX amd64 system to test with but the action seems to build correctly (according to logs): https://github.com/quackscience/duckdb-extension-clickhouse-native/actions/runs/12581017307/job/35064009251

When I look at the community-builder there's something odd indeed: https://github.com/duckdb/community-extensions/actions/runs/12581128135/job/35064325870

```
env:
    VCPKG_TOOLCHAIN_PATH: /Users/runner/work/community-extensions/community-extensions/vcpkg/scripts/buildsystems/vcpkg.cmake
    VCPKG_TARGET_TRIPLET: x64-osx
    OSX_BUILD_ARCH: x86_64
    GEN: ninja
    BUILD_SHELL: 1
    DUCKDB_PLATFORM: osx_amd64
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.11.9/arm64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    VCPKG_DEFAULT_BINARY_CACHE: /Users/runner/work/community-extensions/b/vcpkg_cache
    VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
    ACTIONS_CACHE_URL: https://acghubeus2.actions.githubusercontent.com/6aQ0zYK[5](https://github.com/duckdb/community-extensions/actions/runs/12581128135/job/35064325870#step:18:5)NH98v2mreEr7Nx47GUJviIrbjTG79qYfOWza8YPWrw/
    ACTIONS_RUNTIME_TOKEN: ***
    VCPKG_FORCE_SYSTEM_BINARIES: 1
    RUNVCPKG_VCPKG_ROOT: /Users/runner/work/community-extensions/community-extensions/vcpkg
    VCPKG_ROOT: /Users/runner/work/community-extensions/community-extensions/vcpkg
```

Why would arm64 cache be used for an x86 build? @samansmink does this look normal for the builder? Perhaps this is a cross-platform build but I do not understand the action builder logic much.

@LeeMo2K10 Any chance you could try to build the extension locally to see if this is a code or builder issue?
